import ReduxProvider from '@/redux/provider';
import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className="w-screen min-h-screen text-white overflow-x-hidden overflow-y-auto pb-5">
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
