name: CI Pipeline_staging

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login github registry
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Create .env file
        run: |
          cd back-end && \
          touch .env && \
          echo "PORT=3000" > .env && \
          echo "DATABASE_URL=mongodb+srv://dba_user:dba_db2024@dba.vt1nhtx.mongodb.net/sema" >> .env && \
          echo "DATABASE_URL_DEV=mongodb+srv://dba_user:dba_db2024@dba.vt1nhtx.mongodb.net/sema-dev" >> .env && \
          echo "JWT_SECRET=kaeyros_analytics_2024" >> .env
      - name: Build the Docker image for backend
        run: |
          cd back-end && \
          docker build -t ezekielkaeyros/semabackendrefactor:latest .

      - name: Push to Dockerhub for backend
        run: |
          docker push ezekielkaeyros/semabackendrefactor:latest

